name: CICD Pipeline

on:
  workflow_dispatch:

jobs:
  test-and-build-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: "fs"
          format: "table"
          severity: "HIGH,CRITICAL"
          exit-code: "1"
          ignore-unfixed: false
          skip-files: ""
          skip-dirs: ""

    #   - name: Build with Maven
    #     run: mvn package --file pom.xml

    #   - name: Upload Artifacts to Nexus
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: Boardgame
    #       path: target/*.jar
